### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by AleshaOleg** [AleshaOleg/postcss-sass#38]
Hey, @gucong3000! I what to know what should be done to make a 0.3.0 release.

I planned to make support of loops, variables, list/maps for this release. If I can help with something, just ping me.

Also, would be great, if you will create a small plan what to do needs for the current release. Thanks!

**Comment by gucong3000** [comment]
I think we're ready for the 0.3.0 release just now.
Other new features may be released in  0.4.0

**Comment by gucong3000** [comment]
I just tested the development branch for `stylelint`, there's still a test case that failed.
https://github.com/stylelint/stylelint/pull/2503/files#diff-f2064b230efd41dfa2ca68544e5597b5R58

**Comment by AleshaOleg** [comment]
@gucong3000 I will take a look to this test case in the evening

**Comment by AleshaOleg** [comment]
Hm, are you sure it's the correct syntax for sass?

```
a
  #{$var}: 10px
```

**Comment by AleshaOleg** [comment]
I thought errors occur, because of no var declaration, for this example.

**Comment by AleshaOleg** [comment]
@gucong3000 looks like I'm fixed it.

**Comment by gucong3000** [comment]
after fixed it, a new error was reported
```shell
  ● isStandardSyntaxDeclaration › custom property set in SASS paser

    expect(received).toBeTruthy()

    Expected value to be truthy, instead received
      false

      40 |   it("custom property set in SASS paser", () => {
      41 |     return sassDecls("a\n\t--custom-property-set:\n\t\tcolor: blue", decl => {
    > 42 |       expect(isStandardSyntaxDeclaration(decl)).toBeTruthy();
      43 |     });
      44 |   });
      45 |

      at decl (lib/utils/__tests__/isStandardSyntaxDeclaration.test.js:42:49)
```

**Comment by gucong3000** [comment]
```js
    return sassDecls("a\n\t--custom-property-set:\n\t\tcolor: blue", decl => {
      try {
        expect(isStandardSyntaxDeclaration(decl)).toBeTruthy();
      } catch(ex) {
        console.log(decl.toString());  // => `color: blue`
        console.log(decl.parent.selector);  // => `:`
      }
    });
```
I tried to print out the relevant information

**Comment by gucong3000** [comment]
> after fixed it, a new error was reported

fixed.

**Comment by AleshaOleg** [comment]
So, now everything ready to release?

**Comment by AleshaOleg** [comment]
Are you using Mac? Because build failing - https://www.traviscistatus.com/incidents/mc9x2wmpnvhg

**Comment by AleshaOleg** [comment]
Custom-properties still not working.
https://travis-ci.org/AleshaOleg/postcss-sass/jobs/330794054

**Comment by gucong3000** [comment]
> Custom-properties still not working.

fixed.

> So, now everything ready to release?

yes.

**Comment by AleshaOleg** [comment]
Great! One more I should do is to create ```prepublishOnly ``` script, before release.

**Comment by AleshaOleg** [comment]
Released.
